version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    expose:
      - "15672"
      - "4369"
      - "5671"
      - "25672"
      - "5672"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "25672:25672"
      - "5672:5672"
      - "15672:15672"  
  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: "redis-server /usr/local/etc/redis/redis.conf"       