version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181" 
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"      
    environment:
     ZK_HOSTS: zookeeper:2181      
  kafka:
#    build: .
    image: wurstmeister/kafka:latest    
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
